# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
    - id: trufflehog
      name: TruffleHog
      description: Detect secrets in your data.
      entry: bash -c 'trufflehog https://github.com/poornima-metron/precommit_hooks.git'
      language: system
      stages: ["commit", "push"]

#- repo: local
#  hooks:
#    - id: trufflehog
#      name: TruffleHog
#      description: Detect secrets in your data.
#      entry: bash -c 'trufflehog https://github.com/poornima-metron/precommit_hooks.git'
#      # For running trufflehog in docker, use the following entry instead:
#      # entry: bash -c 'docker run --rm -v "$(pwd):/workdir" -i --rm trufflesecurity/trufflehog:latest git file:///workdir --since-commit HEAD --only-verified --fail'
#      language: system
#      stages: ["commit", "push"]


